-- ==============================================================================
-- SMART HOSTEL COMMAND CENTER - DATABASE INITIALIZATION
-- ORACLE SQL*PLUS COMPATIBLE (Oracle 12c+)
-- ==============================================================================

-- ==============================================================================
-- SAFE DROPS (Ensures cleanly rerunning the script without "already exists" errors)
-- ==============================================================================
BEGIN EXECUTE IMMEDIATE 'DROP TABLE audit_logs CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE announcements CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE activity_logs CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE leave_requests CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE maintenance_tickets CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE allocations CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE rooms CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE users CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/


-- ==============================================================================
-- CREATING TABLES
-- ==============================================================================
CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR2(255) UNIQUE NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    full_name VARCHAR2(255) NOT NULL,
    user_role VARCHAR2(50) DEFAULT 'STUDENT', -- CHANGED from 'role' (Oracle Reserved Keyword)
    permission_flags NUMBER DEFAULT 0, -- Bitwise or integer mapping to permissions
    contact_number VARCHAR2(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE rooms (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_number VARCHAR2(20) NOT NULL,
    floor_number NUMBER NOT NULL,
    block VARCHAR2(10) NOT NULL,
    capacity NUMBER NOT NULL,
    room_type VARCHAR2(20) NOT NULL, -- Examples: '2AC', '3NAC', '4AC', 'WARDEN'
    status VARCHAR2(50) DEFAULT 'AVAILABLE', -- Enum: AVAILABLE, OCCUPIED, MAINTENANCE
    CONSTRAINT rooms_unique UNIQUE (room_number, block)
);

CREATE TABLE allocations (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    room_id NUMBER NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
    allocated_date DATE DEFAULT SYSDATE,
    status VARCHAR2(50) DEFAULT 'ACTIVE' -- Enum: ACTIVE, PAST
);

CREATE TABLE maintenance_tickets (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id NUMBER NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
    user_id NUMBER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    issue_type VARCHAR2(50) NOT NULL,
    description VARCHAR2(4000),
    status VARCHAR2(50) DEFAULT 'OPEN', -- Enum: OPEN, IN_PROGRESS, RESOLVED
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE leave_requests (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    reason VARCHAR2(4000),
    status VARCHAR2(50) DEFAULT 'PENDING', -- Enum: PENDING, APPROVED, REJECTED
    approved_by NUMBER REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE activity_logs (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER REFERENCES users(id) ON DELETE CASCADE,
    action_type VARCHAR2(50) NOT NULL, -- e.g., LATE_ENTRY, TICKET_OPENED
    description VARCHAR2(4000),
    log_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE announcements (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id NUMBER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title VARCHAR2(255) NOT NULL,
    content VARCHAR2(4000) NOT NULL,
    priority VARCHAR2(50) DEFAULT 'LOW', -- Enum: LOW, MEDIUM, HIGH
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE audit_logs (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER REFERENCES users(id) ON DELETE SET NULL,
    action_type VARCHAR2(100) NOT NULL, -- e.g., 'LOGIN', 'ROLE_CHANGE', 'DB_UPDATE'
    table_affected VARCHAR2(50),
    record_id NUMBER,
    old_values VARCHAR2(4000),
    new_values VARCHAR2(4000),
    ip_address VARCHAR2(45),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ==============================================================================
-- INDEXES FOR PERFORMANCE ENHANCEMENT
-- ==============================================================================
CREATE INDEX idx_users_role ON users(user_role);
CREATE INDEX idx_rooms_status ON rooms(status);
CREATE INDEX idx_tickets_status ON maintenance_tickets(status);
CREATE INDEX idx_ac_active ON allocations(status);
